language: python
python:
  - "3.5"
install: easy_install aniso8601 pytz
before_script:
  - cd test
  - cp resources/lrs_properties.py.travis-ci resources/lrs_properties.py
script: python main.py

deploy:
  provider: pypi
  user: edx
  distributions: sdist bdist_wheel
  on:
    tags: true
